name: Comment Workflow

on:
  pull_request_review_comment:
    types: [created]

jobs:
  comment-job:
    runs-on: ubuntu-latest

    steps:
      - name: Display Comment
        env:
          comment: ${{ toJson(github.event.comment) }}
        run: |
          echo "Comment was created on pull request #${{ env.comment.pull_request_url }} by ${{ env.comment.user.login }} with the following content: ${{ env.comment.body }}"
