name: PR Comment Workflow

on:
  pull_request_review_comment:
    types: [created]
  
  issue_comment:
    types: [created]

jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
    - name: Check comment body
      env: 
          GIT_TOKEN: ${{ github.token }}
      run: |
        echo "Checking comment body"
        echo github.event.comment.body: ${{ github.event.comment.body }}
        if echo "${{ github.event.comment.body }}" | grep -q "atlantis plan"; then
          echo "Comment contains atlantis plan"
          echo anuj : $PWD
          pip3 install requests
          python3 ./.github/actions/sample.py
        else
          echo "Comment doesnot contains atlantis plan in it"
        fi
      
 #
 #