name: Comment Workflow

on:
  pull_request_review_comment:
    types: [created]
  #
  # pull_request:
  #   types: [opened]
  issue_comment:
    types: [created]
  

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: alexjurkiewicz/pr-comment-github-deployment@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # - run: 'echo Found it!'
      #   if: steps.check.outputs.triggered == 'true'