name: PR Comment Workflow

on:
  pull_request_review_comment:
    types: [created]
  
  issue_comment:
    types: [created]

jobs:
  run_script:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ github.token }}

    - name: Setup Python
      uses: actions/setup-python@v2.2.2
      with:
        python-version: 3.8
    - name: Execute Python Script
      env: 
        GIT_TOKEN: ${{ github.token }}
      run: |
        echo "Checking comment body"
        echo github.event.comment.body: ${{ github.event.comment.body }}
        if echo "${{ github.event.comment.body }}" | grep -q -E '^atlantis plan'; then
          echo "Comment contains atlantis plan"
          echo pwd : $PWD
          pip3 install requests
          python3 ./.github/actions/sample.py
        else
          echo "Comment doesnot contains atlantis plan in it"
        fi
        pip3 install requests
        python3 ./.github/actions/pr_blocker/scripts/pr_blocker.py

    # - name: Check comment body
    #   env: 
    #       GIT_TOKEN: ${{ github.token }}
    #   run: |
    #     echo "Checking comment body"
    #     echo github.event.comment.body: ${{ github.event.comment.body }}
    #     if echo "${{ github.event.comment.body }}" | grep -q -E '^atlantis plan'; then
    #       echo "Comment contains atlantis plan"
    #       echo pwd : $PWD
    #       python3 ./.github/actions/sample.py
    #     else
    #       echo "Comment doesnot contains atlantis plan in it"
    #     fi
      #
 #
 