name: PR Comment Workflow

on:
  # pull_request_review_comment:
  #   types: [created]
  
  issue_comment:
    types: [created]

jobs:
  comment_checker:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ github.token }}

    - name: Setup Python
      uses: actions/setup-python@v2.2.2
      with:
        python-version: 3.8
    # - name: Check event type
    #   run: |
    #     echo "Event type: ${{ github.event_name }}"
    - name: Get pull request number
      run: |
        echo "Event type: ${{ github.event_name }}"
        # echo $env
        # env
        # echo "${{github.event.number }}"
        echo PR number is :"${{github.event.issue.number}}"
        

    - name: Execute Python Script
      env: 
        GIT_TOKEN: ${{ github.token }}
        GITHUB_EVENT_PULL_REQUEST_NUMBER: "${{github.event.issue.number}}"
      run: |
        echo "Checking comment body"
        echo github.event.comment.body: ${{ github.event.comment.body }}
        echo pr number "${{github.event.issue.number}}"

        env | grep GITHUB_EVENT_PULL_REQUEST_NUMBER
        if echo "${{ github.event.comment.body }}" | grep -q -E '^atlantis plan'; then
          echo "Comment contains atlantis plan"
          echo pwd : $PWD
          pip3 install requests
          python3 ./.github/actions/triggered_comment.py
        elif echo "${{ github.event.comment.body }}" | grep -q -E '^atlantis apply'; then
          echo "Comment contains atlantis apply"
          echo pwd : $PWD
          #write a logic to check whether atlantis apply ran successfully or not
          #if it ran successfully then run atlantis plan and check the drift
          pip3 install requests
          python3 ./.github/actions/atlantis_apply.py
        else
          echo "Comment doesnot contains atlantis plan or atlantis apply in it"
        fi
        
###########
 