name: PR Close Alert

on:
  pull_request:
    types: [closed]

jobs:
  alert:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git
        uses: actions/checkout@v2

      - name: Create a comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          body: |
            PR #${{ env.GITHUB_EVENT_NUMBER }} has been closed.

      - name: Display a message
        run: |
          echo "Comment added to PR #${{ env.GITHUB_EVENT_NUMBER }}."
