name: PR Close Alert

on:
  pull_request:
    types: [closed]

jobs:
  alert:
    runs-on: ubuntu-latest

    steps:
      - name: Display a message
        run: |
          echo "PR #${{ env.GITHUB_EVENT_NUMBER }} has been closed.."
