name: SDLC
on: 
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - reopened

jobs:
  check_prs:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ github.token }}

      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.8
      - name: Execute Python Script
        env: 
          GIT_TOKEN: ${{ github.token }}
          AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
          # AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_KEY2 }}
        run: |
          pip3 install requests
          pip3 install boto3

          python3 ./.github/actions/PR_created.py