name: SDLC
on:
  pull_request:
    types:
      - opened
      - reopened

jobs:
  check_prs:
    runs-on: [self-hosted]
    permissions: write-all
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ github.token }}

      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.8
      - name: Execute Python Script
        env: 
          GIT_TOKEN: ${{ github.token }}
         
        run: |
          pip3 install requests
          python3 ./.github/actions/sample.py