name: SDLC
on:
  pull_request:
    types:
      - opened
      - reopened

jobs:
  check_prs:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ github.token }}

      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.8
      - name: Execute Python Script
        env: 
          GIT_TOKEN: ${{ github.token }}


        id: files
        uses: jitterbit/get-changed-files@v1
      - run: |
          pip3 install requests
          python3 ${{ github.workspace }}/.github/actions/sample.py ${{ steps.files.outputs.all }}
        
        # run: |
        #   pip3 install requests
        #   python3 ./.github/actions/sample.py